import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { 
  Bell, ShieldAlert, AlertTriangle, AlertCircle, CheckCircle2, 
  ChevronRight, Filter, Check, RefreshCw
} from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

export default function AlertsPage() {
  const { t } = useLanguage();
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedSeverity, setSelectedSeverity] = useState('All');

  useEffect(() => {
    fetchAlerts();
  }, [selectedSeverity]);

  const fetchAlerts = async () => {
    try {
      setLoading(true);
      let url = '/api/alerts?';
      if (selectedSeverity !== 'All') url += `severity=${selectedSeverity}&`;
      const res = await axios.get(url);
      setAlerts(res.data);
    } catch (err) {
      console.error("Error fetching alerts:", err);
    } finally {
      setLoading(false);
    }
  };

  const markAsRead = async (alertId) => {
    try {
      await axios.put(`/api/alerts/${alertId}/read`);
      setAlerts(alerts.map(a => a.id === alertId ? { ...a, is_read: true } : a));
    } catch (err) {
      console.error("Error marking alert as read:", err);
    }
  };

  const getSeverityIcon = (sev) => {
    if (sev === 'Critical' || sev === 'High') return <AlertTriangle className="w-5 h-5 text-red-500" />;
    if (sev === 'Warning') return <AlertCircle className="w-5 h-5 text-amber-500" />;
    return <CheckCircle2 className="w-5 h-5 text-emerald-500" />;
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
      
      {/* Title & Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-800 flex items-center gap-2">
            <Bell className="w-6 h-6 text-red-500" />
            <span>{t('alertsTitle', 'Early Warning Alerts Stream')}</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            {t('alertsSubtitle', 'Automated threshold breach flags generated by DRISHTI ML engine.')}
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5 text-xs text-slate-500">
            <Filter className="w-3.5 h-3.5" />
            <select
              value={selectedSeverity}
              onChange={(e) => setSelectedSeverity(e.target.value)}
              className="bg-white border border-slate-200 rounded-xl px-3 py-2 text-xs text-slate-700 focus:outline-none focus:border-blue-400"
            >
              <option value="All">{t('alertAllSeverities', 'All Severities')}</option>
              <option value="Critical">{t('alertCritical', 'Critical Only')}</option>
              <option value="Warning">{t('alertWarning', 'Warning Only')}</option>
              <option value="Info">{t('alertInfo', 'Info Only')}</option>
            </select>
          </div>

          <button
            onClick={fetchAlerts}
            className="p-2 rounded-xl bg-white hover:bg-slate-50 text-slate-500 border border-slate-200 transition-all shadow-sm"
            title="Refresh Feed"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Alerts Feed List */}
      <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-sm space-y-4">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-16 gap-3">
            <div className="w-8 h-8 border-3 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
            <p className="text-xs text-slate-400 font-mono">{t('alertScanning', 'Scanning risk alert log...')}</p>
          </div>
        ) : alerts.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center space-y-3">
            <CheckCircle2 className="w-12 h-12 text-emerald-400" />
            <h3 className="text-base font-bold text-slate-600">{t('alertNoAlerts', 'No Alerts Flagged')}</h3>
            <p className="text-xs text-slate-400">{t('alertNoAlertsSub', 'All monitored projects are operating within expected risk parameters.')}</p>
          </div>
        ) : (
          <div className="space-y-3">
            {alerts.map((a) => (
              <div
                key={a.id}
                className={`p-4 rounded-xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                  !a.is_read
                    ? 'bg-white border-slate-200 shadow-sm'
                    : 'bg-slate-50 border-slate-100 opacity-70'
                }`}
              >
                <div className="flex items-start gap-3.5">
                  <div className="mt-0.5">{getSeverityIcon(a.severity)}</div>
                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-bold text-sm text-slate-800">{a.title}</span>
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold font-mono ${
                        a.severity === 'Critical' ? 'bg-red-50 text-red-600 border border-red-200' :
                        a.severity === 'Warning' ? 'bg-amber-50 text-amber-600 border border-amber-200' :
                        'bg-slate-100 text-slate-500 border border-slate-200'
                      }`}>
                        {a.severity}
                      </span>
                      {!a.is_read && (
                        <span className="px-1.5 py-0.5 rounded text-[9px] bg-red-500 text-white font-bold">
                          NEW
                        </span>
                      )}
                    </div>

                    <p className="text-xs text-slate-500 leading-relaxed">{a.message}</p>

                    <div className="flex items-center gap-3 text-[10px] text-slate-400 font-mono">
                      <span>Project: {a.project_code} ({a.project_name})</span>
                      <span>•</span>
                      <span>{new Date(a.created_at).toLocaleString()}</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2 self-end sm:self-center">
                  {!a.is_read && (
                    <button
                      onClick={() => markAsRead(a.id)}
                      className="px-3 py-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-600 text-xs font-semibold flex items-center gap-1 border border-slate-200 transition-all"
                    >
                      <Check className="w-3.5 h-3.5" />
                      <span>{t('btnMarkRead', 'Mark Read')}</span>
                    </button>
                  )}

                  <Link
                    to={`/projects/${a.project_id}`}
                    className="px-3 py-1.5 rounded-lg bg-blue-50 hover:bg-blue-600 text-blue-600 hover:text-white border border-blue-200 text-xs font-semibold flex items-center gap-1 transition-all"
                  >
                    <span>{t('btnViewProject', 'View Project')}</span>
                    <ChevronRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}
